adminUser:
  password: vault:pr-147-43-boot-gke-jxui/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-147-43-boot-gke-jxui/pipelineUser:token
  username: cjxd-bot-test
prow:
  hmacToken: vault:pr-147-43-boot-gke-jxui/prow:hmacToken
